### ISSUE TITLE
Database tag is missing in schema files

### ISSUE THREAD

**Issue by Gusser93** [FZJ-JSC/JUBE#1]
When using the new database tag, I noticed that the scheme files (the .dtd in my case) are missing the database tag. I am using the scheme files from commit [ed2017c](https://github.com/FZJ-JSC/JUBE/commit/ed2017c596fd1cc84fd61010eef717273c1346d1).

**Comment by thobreuer** [comment]
Thanks for reporting. Fix in https://github.com/FZJ-JSC/JUBE/commit/fdc2c1171e3a6a658a435fa276520b526ea969f1 as part of `REL-2.6.0`.
