### ISSUE TITLE
Empty exported parameters break $jube_wp_envstr

### ISSUE THREAD

**Issue by schwitanski** [FZJ-JSC/JUBE#3]
Using `export="true"` with an empty parameter breaks `$jube_wp_envstr`. For example, having three exported parameters `ENV1=foo`, `ENV2=` (empty) and `ENV3=bar` leads to:

```
export ENV1="foo"
export ENV2="export ENV3=bar"
```

MWE, tested with 2.5.1:

```
<?xml version="1.0" encoding="UTF-8"?>
<jube>
  <benchmark name="mwe_export" outpath="bench_run">
    <parameterset name="test_pset">
      <parameter name="ENV1" export="true">foo</parameter>
      <parameter name="ENV2" export="true"></parameter>
      <parameter name="ENV3" export="true">bar</parameter>
    </parameterset>

    <step name="test">
      <use>test_pset</use>
      <do>echo '$jube_wp_envstr'</do>
    </step>    
  </benchmark>
</jube>
```

Inspect `run.log` or `stdout` of the step. When setting `ENV2` to any non-empty value, it works again as expected.

**Comment by thobreuer** [comment]
Thanks for reporting. Fixed in https://github.com/FZJ-JSC/JUBE/commit/c05e510bace667fa89b310c0aa6e7b6f6e35ae5d as part of REL-2.6.0.
