### ISSUE TITLE
`check_tags` fails randomly

### ISSUE THREAD

**Issue by simon-schlepphorst** [FZJ-JSC/JUBE#8]
`check_tags` fails randomly on this slightly more involved example.

Reproducer:
```
# jube-test.yaml
check_tags: ((local | (jureca + dc-cpu)) + (gcc | clang)) | (jureca + (dc-gpu,login-gpu) + (nvcc | clang))
name: jube-test
outpath: jube_output
```
`jube run jube-test.yaml`

**Comment by thobreuer** [comment]
- Comma is not a supported symbol in `check_tags`. We will consider whether to print an error message in this case.
- For backward compatibility, comma is still allowed in `tag`, but we are thinking about deprecating it. 
- Exclusive OR for `check_tags` and `tag` is not implemented in JUBE yet. 
- Individual `tag` also have no dependencies on each other.

**Comment by thobreuer** [comment]
Here are some updates from the new release: https://github.com/FZJ-JSC/JUBE/releases/tag/REL-2.7.0
- The use of commas in `<check_tags>` and `tag` attributes is no longer allowed.
- `^` can now be used as an exclusive disjunction (xor).
- A new `<tags>` tag has been added, which includes the new `<tag>` tag to write a description for each tag attribute specified in the input file. The description can be displayed with the new command line call `jube tag`.
- see also the tagging example in the advanced tutorial: https://apps.fz-juelich.de/jsc/jube/docu/advanced.html#tagging
